### ISSUE TITLE
Missing Panel on New Account

### ISSUE THREAD

**Issue by theemack** [petazeta/youronlineshop#11]
It appears only the default users webadmin...systemadmin...are the only ones that can make a purchase, the new account registrar cannot confirm the order or proceed as there is a missing panel to add details name...address...etc...the issue behaves the same on the your demo site ... but shows clearly in your video that this is the process to check out.

Regards.

**Comment by petazeta** [comment]
Hello theemakck!!
Nice to hear from you. I am aware of the problem more or less. I am working in a new version, and while working on it, I detected the problem for new users and I fixed for the new version. But for the currentversion I am not going to fix it cause however no people except you is using it. But new version will be available soon. :)

**Comment by petazeta** [comment]
I finally fixed the error and commit changes. Thank theemack for your report.
![Captura de pantalla de 2021-11-23 01-04-33](https://user-images.githubusercontent.com/5184927/142953798-8c901557-240a-4aba-971f-ec16e61987cf.png)
