### ISSUE TITLE
Page title disappears

### ISSUE THREAD

**Issue by theemack** [petazeta/youronlineshop#12]
Seasons greetings Alberto!

I've noticed that when using html snippets to copy and paste, the page title disappears. Upon refresh a few elements become void and since I'm not a coder I'm not sure where to correct this.

Another option would be to add variants and sizes.

**Comment by petazeta** [comment]
:) thank you! Also greetings for you!
I have notice this issue. I am kind of aware of it. You can easily solve temporary by editing file:
https://github.com/petazeta/youronlineshop/blob/master/themes/root/views/toph1.html
This files define the behaviour of that element. So you can change code for example:
Remove (or comment with //) line 11, this code:
`visibleOnMouseOver({element: thisElement.parentElement.querySelector('[data-id=butedit]'), parent: thisElement.parentElement});`
Once you remove this behaviour I guess that the edition button will appear show you can change the element content

**Comment by petazeta** [comment]
Another option without touching code is by using chrome dev tools. So you can inspect that element:
`<div data-id="butedit" class="btmiddleright"></div>`
And give it the attribute opacity: 1, than the edition will appear for you. But make sure you are logged in with web administration user.

**Comment by petazeta** [comment]
Next versions of the software wont suppoort php, will only be released in node.js

**Comment by petazeta** [comment]
This issue is already fixed
