### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by theemack** [petazeta/youronlineshop#7]
I must say I love this App, the demo is fantastic being playing around with it over the weekend, decided to try and install it on my hosted server via cpanel on namecheap, followed instructions to the T but with no luck. Its been populating the database for hours despite the database imported and installed.

Any other way to do this or am i just missing something obvious?

**Comment by petazeta** [comment]
Hello theemack,
thank you very much for trying the app and giving feedback. For me the app works fine, but I don't have much experience in other servers so... better for me if I can get access to the server itself or so. I must say that I am aware of your problem cause I monitor yos installations in order to check posible problems and it seems that your installation doesn't archive the database population. Have you tryied to import the database.sql manually?

**Comment by theemack** [comment]
Petazeta - your instant reply is appreciated, deeply appreciated.

I have imported the database.sql as per your instructions then tried several ways and also changed the php versions but have had no luck.

1:   backend/utils/database.sql

2:   backend/utils/datables_tables.php

![screenshot-lo4](https://user-images.githubusercontent.com/7733293/133237609-1a78519f-5682-428e-ab4b-81ea73abbdfe.png)

![screenshot-lo2](https://user-images.githubusercontent.com/7733293/133236586-13ec90c4-a45e-432d-89a3-9a0c712ba176.png)

![screenshot-lo3](https://user-images.githubusercontent.com/7733293/133236588-5ccec04a-e7e1-46fa-9ac8-b0a2d3abb970.png)

**Comment by theemack** [comment]
Correction:
I meant to say that I have imported the database.sql manually from the 
**backend/utils/database.sql**   ---- this fails 

with that failing i tried the other folder **backend/includes/database_tables.php** ------ this fails too

on all attempts i **create the required mysql database** with relevant info but it does not make a difference to the install other than the wait option.

**Comment by petazeta** [comment]
Hi :),
database_tables.php is not for being imported. That said, I think the problem is that your database doesn't allow the kind of relationships. I tryed hosted yos in free servers and I had that problems, the mysql system were not ok about the kind of relationships. I can install yos for you in my servers if you want to, and I can host also the domain, I want people to use the system so for me it will be a good deal, cheers.

**Comment by theemack** [comment]
> Petazeta - your instant reply is appreciated, deeply appreciated.
> 
> I have imported the database.sql as per your instructions then tried several ways and also changed the php versions but have had no luck.
> 
> 1: backend/utils/database.sql
> 
> 2: backend/utils/datables_tables.php
> 
> ![screenshot-lo4](https://user-images.githubusercontent.com/7733293/133237609-1a78519f-5682-428e-ab4b-81ea73abbdfe.png)
> 
> ![screenshot-lo2](https://user-images.githubusercontent.com/7733293/133236586-13ec90c4-a45e-432d-89a3-9a0c712ba176.png)
> 
> ![screenshot-lo3](https://user-images.githubusercontent.com/7733293/133236588-5ccec04a-e7e1-46fa-9ac8-b0a2d3abb970.png)

**Comment by theemack** [comment]
> Hi :),
> database_tables.php is not for being imported. That said, I think the problem is that your database doesn't allow the kind of relationships. I tryed hosted yos in free servers and I had that problems, the mysql system were not ok about the kind of relationships. I can install yos for you in my servers if you want to, and I can host also the domain, I want people to use the system so for me it will be a good deal, cheers.

Just in observation, if the link for the database is located here **backend/utils/database.sql** is their a reason the install directives are searching for **includes/database.sql.** Would this be the problem that there is an issue despite having imported it manually or clicking the link that request to populate the database??
![screenshot-lo3](https://user-images.githubusercontent.com/7733293/133255931-015f60c9-fda7-4a1a-ad89-873ed1623b99.png)

**Comment by petazeta** [comment]
I have detected an error at installation instructions (troubleshooting): it says database.php, when it sould say backend/utils/database.sql. If you can import this file, then that's all for installation, no need for any more installation proccess anymore. Installation process is just importing this file, that can be done manually or by the installer.

**Comment by petazeta** [comment]
And also there is an error at the button label includes/database.sql, it should say the same: backend/utils/database.sql

**Comment by theemack** [comment]
> I have detected an error at installation instructions (troubleshooting): it says database.php, when it sould say backend/utils/database.sql. If you can import this file, then that's all for installation, no need for any more installation proccess anymore. Installation process is just importing this file, that can be done manually or by the installer.


Good day to you Petazeta
![screenshot-2021 0](https://user-images.githubusercontent.com/7733293/133408304-f472af6e-61e7-4368-b576-9fdbe6088deb.png)
![screenshot-2021 1](https://user-images.githubusercontent.com/7733293/133408306-e006d807-12b8-4f68-bc19-e6af2e5b6e12.png)
![screenshot-2021 2](https://user-images.githubusercontent.com/7733293/133408307-9da6759c-3535-4ac0-8044-52e900e13485.png)

Not giving up on your App, still attempting to do as you instructed and this time I have tried on 3 different server providers.
1: namecheap
2: hyperpage
3: bitnami lamp stack

The same errors appear despite the database imported from **backend/utils/database.sql** showing success. Once all done go to the url and the error tab appears with java-script errors as per images below, from this point there is no box to select a choice instead error flags.

**Comment by petazeta** [comment]
Give me access to some of these servers: melchorherrera@gmail.com
I will get the issue and then I could fix it.
